/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "The Fellowship",
  "tagline": "A Coliving Community in Travis Heights, Austin",
  "favicon": "img/favicon.ico",
  "url": "https://your-org.github.io",
  "baseUrl": "/community-house/",
  "organizationName": "your-org",
  "projectName": "community-house",
  "deploymentBranch": "gh-pages",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "path": "docs",
          "routeBasePath": "spaces",
          "editUrl": "https://github.com/your-org/community-house/tree/main/"
        },
        "blog": {
          "showReadingTime": true,
          "blogTitle": "Community Updates",
          "blogDescription": "News, events, and updates from our community",
          "postsPerPage": 10,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://github.com/your-org/community-house/tree/main/"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "plugins": [
    "@docusaurus/plugin-ideal-image",
    null
  ],
  "themeConfig": {
    "image": "img/social-card.jpg",
    "metadata": [
      {
        "name": "keywords",
        "content": "coliving, coworking, community, housing"
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      {
        "property": "og:type",
        "content": "website"
      }
    ],
    "navbar": {
      "title": "The Fellowship",
      "logo": {
        "alt": "The Fellowship Logo",
        "src": "img/logo.svg",
        "srcDark": "img/logo-dark.svg"
      },
      "items": [
        {
          "to": "/",
          "label": "Home",
          "position": "left",
          "activeBasePath": "none"
        },
        {
          "type": "docSidebar",
          "sidebarId": "spacesSidebar",
          "position": "left",
          "label": "Spaces"
        },
        {
          "to": "/location",
          "label": "Location",
          "position": "left"
        },
        {
          "to": "/membership",
          "label": "Membership",
          "position": "left"
        },
        {
          "to": "/events",
          "label": "Events",
          "position": "left"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "to": "/about",
          "label": "About",
          "position": "left"
        },
        {
          "href": "/apply",
          "label": "Apply Now",
          "position": "right",
          "className": "navbar-cta-button"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Explore",
          "items": [
            {
              "label": "Spaces",
              "to": "/spaces/spaces"
            },
            {
              "label": "Location",
              "to": "/location"
            },
            {
              "label": "Membership",
              "to": "/membership"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Events",
              "to": "/events"
            },
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "About",
              "to": "/about"
            }
          ]
        },
        {
          "title": "Connect",
          "items": [
            {
              "label": "Twitter",
              "href": "https://twitter.com/yourhandle"
            },
            {
              "label": "Instagram",
              "href": "https://instagram.com/yourhandle"
            },
            {
              "label": "Email Us",
              "href": "mailto:hello@communityhouse.com"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 The Fellowship. All Rights Reserved."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "announcementBar": {
      "id": "announcement",
      "content": "Now accepting applications — rooms starting at $750/month. <a href=\"/apply\">Apply today</a>",
      "backgroundColor": "#E85D04",
      "textColor": "#FFFFFF",
      "isCloseable": true
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
